.\"
.\" Copyright (C) 2008 Robert Millan
.\"
.\" Permission to use, copy, modify, distribute, and sell this software
.\" and its documentation for any purpose is hereby granted without fee,
.\" provided that the above copyright notice appear in all copies and
.\" that both that copyright notice and this permission notice appear
.\" in supporting documentation.  The author makes no representations
.\" about the suitability of this software for any purpose.  It is
.\" provided "as is" without express or implied warranty.
.\"
.\"
.TH bin2h 1 "November 26, 2012"
.SH NAME
bin2h \- converter to header file
.SH SYNOPSIS
.B bin2h <bytes_per_line> < input > output
.SH DESCRIPTION
.PP
bin2h converts input to bytewise output with <bytes_per_line> on each
line.
.SH AUTHORS
Copyright (C) 2008 Robert Millan
This manual page was written by Thorsten Alteholz <debian@alteholz.de>,
for the Debian GNU/Linux system (but may be used by others).
